---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: frontend_install
  commands:
    - yarn
- name: frontend_build
  commands:
    - yarn build

trigger:
  branch:
    - master
    - drone-test
  event:
    include:
      - pull_request
