---
kind: pipeline
type: docker
name: seasoned build

platform:
  os: linux
  arch: amd64

steps:
  - name: Frontend install
    image: node:18.2.0
    commands:
      - node -v
      - yarn --version
      - yarn

  - name: Frontend build
    image: node:18.2.0
    commands:
      - node -v
      - yarn --version
      - yarn
      - yarn build

  - name: Lint project using eslint
    image: node:18.2.0
    commands:
      - yarn lint
    failure: ignore

  - name: Build and publish docker image
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/kevinmidboe/seasoned
      dockerfile: Dockerfile
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_PASSWORD
      tags: latest

  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    secrets:
      - ssh_key
    when:
      event:
        - push
      branch:
        - master
        - drone-test
      status: success
    settings:
      host: 10.0.0.114
      username: root
      key:
        from_secret: ssh_key
      command_timeout: 600s
      script:
        - /home/kevin/deploy/seasoned.sh

trigger:
  event:
    include:
      - push
      # - pull_request
